' autorun.brs - BrightSign Series 5 launcher for flutter_signage_app
' Method: Method 1 - Flutter Web Adaptation (HTML renderer, static files)
' Target: BrightSign Series 5 (OS 9+)
' Resolution: 1920x1080
'
' Generated by: Flutter/Dart Migration Guide - Method 1
' Source app: flutter_signage_app v1.0.0+1
' Build type: Flutter Web HTML renderer (no CanvasKit)
'
' SD card structure:
'   autorun.brs          <- this file
'   index.html           <- Flutter Web entry point (BrightSign-adapted)
'   flutter.js           <- Flutter engine loader
'   flutter_bootstrap.js <- Flutter init (service worker removed)
'   main.dart.js         <- Compiled Dart application
'   assets/              <- Flutter bundled assets (fonts, etc.)

sub Main()
    ' Set display resolution
    SetResolution()

    ' Launch Flutter Web app in BrightSign HTML widget
    LaunchFlutterWebApp()
end sub

sub SetResolution()
    di = CreateObject("roDeviceInfo")
    dm = CreateObject("roDisplayMode")
    dm.SetMode("1920x1080x60p")
end sub

sub LaunchFlutterWebApp()
    msgPort = CreateObject("roMessagePort")

    ' Configure HTML widget for Flutter Web
    rect = CreateObject("roRectangle", 0, 0, 1920, 1080)
    config = CreateObject("roAssociativeArray")
    config.url = "file:///sd:/index.html"
    config.port = msgPort

    ' Enable remote inspector for debugging (Chrome DevTools on port 2999)
    inspectorServer = CreateObject("roAssociativeArray")
    inspectorServer.port = 2999
    config.inspector_server = inspectorServer

    ' Create and show HTML widget
    widget = CreateObject("roHtmlWidget", rect, config)
    widget.Show()

    ' Event loop - keep app running
    while true
        msg = wait(0, msgPort)
        if type(msg) = "roHtmlWidgetEvent" then
            HandleHtmlEvent(msg, widget)
        end if
    end while
end sub

sub HandleHtmlEvent(msg as object, widget as object)
    eventData = msg.GetData()
    reason = eventData.reason

    if reason = "load-error" then
        print "HTML widget load error: "; eventData.url
    else if reason = "dialog" then
        ' Dismiss any unexpected dialogs
        widget.SendJavascriptMessage("OK")
    end if
end sub
