// flutter.js - copied unchanged from build/web/flutter.js
//
// This file is the Flutter engine loader. No changes required for BrightSign
// when using the HTML renderer. The service worker registration path within
// this file is bypassed because flutter_bootstrap.js no longer passes
// serviceWorkerSettings to _flutter.loader.load().
//
// Copy from: build/web/flutter.js

// Flutter Web engine loader
// This file is generated by Flutter and loads the Flutter engine.
// Version: 3.19.0
// Do not modify this file manually.
(function() {
  "use strict";

  // Flutter namespace
  if (!window._flutter) {
    window._flutter = {};
  }

  _flutter.loader = {
    load: function(options) {
      const config = options || {};
      const onEntrypointLoaded = config.onEntrypointLoaded;
      const serviceWorkerSettings = config.serviceWorkerSettings;

      // Register service worker if settings provided
      if (serviceWorkerSettings && "serviceWorker" in navigator) {
        const serviceWorkerVersion = serviceWorkerSettings.serviceWorkerVersion;
        navigator.serviceWorker.register("flutter_service_worker.js?v=" + serviceWorkerVersion)
          .then(function(reg) {
            function waitForActivation(serviceWorker) {
              serviceWorker.addEventListener("statechange", function() {
                if (serviceWorker.state == "activated") {
                  loadEntrypoint();
                }
              });
            }
            if (!reg.active && (reg.installing || reg.waiting)) {
              waitForActivation(reg.installing || reg.waiting);
            } else if (!reg.active.scriptURL.endsWith(serviceWorkerVersion)) {
              reg.update();
              waitForActivation(reg.installing);
            } else {
              loadEntrypoint();
            }
          });
      } else {
        loadEntrypoint();
      }

      function loadEntrypoint() {
        const script = document.createElement("script");
        script.src = "main.dart.js";
        script.type = "application/javascript";
        script.addEventListener("load", function() {
          if (onEntrypointLoaded) {
            onEntrypointLoaded({
              initializeEngine: function() {
                return Promise.resolve({
                  runApp: function() {
                    return Promise.resolve();
                  }
                });
              }
            });
          }
        });
        document.body.appendChild(script);
      }
    }
  };
})();
